# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env:
  ACCEPT_EULA: "Y"
  MSSQL_ENABLE_HADR: "1"
  MSSQL_AGENT_ENABLED: "1"
  MSSQL_SA_PASSWORD: "Aa123456"